version: '3.8'

services:
  odoo16:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8070:8069"
    volumes:
      - odoo16-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - odoo16-logs:/var/log/odoo
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    command: odoo -c /etc/odoo/odoo.conf
    restart: always

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo16
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5433:5432"
    volumes:
      - odoo16-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  odoo16-web-data:
    name: odoo-16-docker_odoo16-web-data
  odoo16-logs:
    name: odoo-16-docker_odoo16-logs
  odoo16-db-data:
    name: odoo-16-docker_odoo16-db-data
