[options]
; Puerto en el que se ejecutará Odoo dentro del contenedor (no expuesto fuera)
http_port = 8069

; Nombre de la base de datos para Odoo 16
db_name = odoo16

; Usuario y contraseña para la conexión a la base de datos
db_user = odoo
db_password = odoo
db_host = db
db_port = 5432

; Contraseña maestra para Odoo
admin_passwd = admin

; Directorio de complementos
addons_path = /mnt/extra-addons

; Ruta para guardar datos persistentes de Odoo
data_dir = /var/lib/odoo

; Configuración del registro (opcional)
logfile = /var/log/odoo/odoo16.log
log_level = info

; Configuración para desarrolladores (opcional)
developer_mode = True
